version: "3"

services:
  ms-nodebootstrap-example:
    container_name: ms-nodebootstrap-example
    build:
      context: .
    volumes:
      - ./:/opt/code
      #- /opt/code/node_modules
    expose:
      - 5501
    ports:
      - 5501:5501
    env_file:
      - ./database.env
    links: 
      - ms-nodebootstrap-example-db
    environment: 
      - NODE_ENV=development
      - NODE_HOT_RELOAD=1
      - NODE_LOGGER_GRANULARLEVELS=1
      - NODE_CONFIG_DISABLE_FILE_WATCH="Y"
      - PORT=5501
    command: nodemon -L -e js,coffee,jade,handlebars server.js

  ms-nodebootstrap-example-db:
    container_name: ms-nodebootstrap-example-db
    image: mysql:5.7
    # port mapping not needed for the app, but convenient in debugging
    # to use some GUI tool (e.g. SequelPro) against the DB, on the host
    ports:
      - 5306:3306
    env_file:
      - ./database.env
    volumes:
      - ms_nb_example_db_data:/var/lib/mysql
    restart: always

volumes:
  ms_nb_example_db_data: